### ISSUE TITLE
Packagist entry needs a refresh

### ISSUE THREAD

**Issue by jobee** [schemaio/schema-php-client#2]
@ericingram thanks for the autoloading fix #1 

In order to install the package via composer.json without adding the github repo link manually (as you recommend in the readme), you have to update the packagist entry (not sure about, but: shouldn't that happen automatically?)
https://packagist.org/packages/schemaio/schema-php-client

**Comment by ericigg** [comment]
@jobee I'm not sure I understand what you mean, what about it needs to be updated?

**Comment by ericingram** [comment]
@jobee I'm not sure I understand what you mean, what about it needs to be updated?

**Comment by jobee** [comment]
@ericingram when you trying to install the package via composer, the dev-master is still on the old commit...

it seems you have to options... clicking the "force update" button on packagist each time you push a commit to github or setup a github service hook to notify packagist on repository updates automatically
https://packagist.org/about

![packagist-schemaio](https://cloud.githubusercontent.com/assets/5636715/17454673/1789958c-5b9f-11e6-931a-21a545603985.png)

**Comment by ericingram** [comment]
It looks like the packagist entry was created and owned by @pedro-santiago --

Hey Pedro! Can you grant us maintainer access so we can update this? Thanks!

**Comment by pedro-santiago** [comment]
Hey guys! Sorry about the delay. I have removed myself from it so this way you can properly integrate it with github directly and avoid this problem in the future. 

Happy Integration ^^

**Comment by ericingram** [comment]
Thank you @pedro-santiago! This is now fixed and setup for auto publish.
